### ISSUE TITLE
state : Cancel timelock is expired

### ISSUE THREAD

**Issue by fbion** [comit-network/xmr-btc-swap#709] opened 2021-08-30 09:15 UTC
Error: Failed to broadcast Bitcoin cancel transaction 

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))

**Comment by fbion** [comment] 2021-08-30 09:21
ERROR The cancel transaction cannot be published yet, because the timelock has not expired. Please try again later

**Comment by fbion** [comment] 2021-08-30 13:18
2021-08-30 21:13:41  INFO Received new confirmation for Monero lock tx txid= seen_confirmations=7 needed_confirmations=10
2021-08-30 21:15:52  WARN Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
	- CloseNotify alert received
 txid=
Error: Failed to complete swap

Caused by:
    0: Failed to broadcast Bitcoin cancel transaction 
    1: Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))

**Comment by kirtspaulding** [comment] 2021-08-30 18:59
Hi I am having the same issue. Transaction was working properly and failed.

Error: Failed to broadcast Bitcoin cancel transaction ae3a078c9a626a3299d641fd98148a8ac07d0c6ba321ddea8b2b2e28942b49db

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))
    
 Says I can't cancel because timelock hasn't expired? I can't resume the swap either.

**Comment by devbordecraft** [comment] 2021-08-30 19:04
Check this out :
https://sethforprivacy.com/guides/bitcoin-monero-atomic-swaps/#what-to-do-if-the-swap-fails

You can refund between 72 and 128 of your first bitcoin transaction

**Comment by kirtspaulding** [comment] 2021-08-30 19:08
> Check this out :
> https://sethforprivacy.com/guides/bitcoin-monero-atomic-swaps/#what-to-do-if-the-swap-fails
> 
> You can refund between 72 and 128 of your first bitcoin transaction

Yep great, I need to wakeup at in the middle of the night to ensure I don't lose my money.

**Comment by devbordecraft** [comment] 2021-08-30 19:11
Not necessarily, a 72 confirmation is about ~12hours.
Out of curiosity, what error message does it show to you when you try to resume?

**Comment by kirtspaulding** [comment] 2021-08-30 19:13
@devbordecraft 

swaptool> ./swap.exe resume --swap-id 4a6bbdec-341b-4d18-bfef-b460a3050717

Error: Failed to broadcast Bitcoin cancel transaction ae3a078c9a626a3299d641fd98148a8ac07d0c6ba321ddea8b2b2e28942b49db

Caused by:
    Electrum(Protocol(String("sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-BIP68-final\"}")))

**Comment by devbordecraft** [comment] 2021-08-30 19:47
Maybe it is related to this ?
https://medium.com/@harshg0910/click-to-pause-execution-in-windows-powershell-b451044501ac
If that's it, that would explain why the swap failed

**Comment by kirtspaulding** [comment] 2021-08-30 20:40
@devbordecraft this is a great comment. I can't say if it's the right answer, but if clicking the session or clicking away causes issues... should be high priority for devs to investigate.

**Comment by devbordecraft** [comment] 2021-08-30 21:53
Afaik this is a bug (or a feature ?) related to windows PowerShell, not the tool. PowerShell suspend any process in the console when the user select or highlight something in it

**Comment by rishflab** [comment] 2021-08-31 00:01
https://github.com/comit-network/xmr-btc-swap/pull/705 



> 2021-08-30 21:13:41 INFO Received new confirmation for Monero lock tx txid= seen_confirmations=7 needed_confirmations=10
> 2021-08-30 21:15:52 WARN Failed to get status of script: Failed to subscribe to header notifications: Made one or multiple attempts, all errored:
> - CloseNotify alert received
> txid=
> Error: Failed to complete swap
> 
> Caused by:
> 0: Failed to broadcast Bitcoin cancel transaction
> 1: Electrum(Protocol(String("sendrawtransaction RPC error: {"code":-26,"message":"non-BIP68-final"}")))

We think we have the error causing this and have a fix coming shortly https://github.com/comit-network/xmr-btc-swap/pull/705

**Comment by fbion** [comment] 2021-08-31 01:03
./swap --debug cancel --swap-id **
Error: Cannot cancel swap ** because it is in state btc is cancelled which is not refundable.

./swap --debug refund --swap-id **
2021-08-31 08:38:24 Published Bitcoin transaction txid=** kind=refund
2021-08-31 08:38:24 Waiting for Bitcoin transaction finality txid=** required_confirmation=2
2021-08-31 08:42:28 Waiting for Bitcoin transaction finality txid=** seen_confirmations=2 needed_confirmations=2
Done: BtcRefunded

**Comment by nanostos** [comment] 2021-08-31 05:29
I guess we can remove the loss-of-funds tag now. It's not a powershell issue. I've experienced the same exact problem on both Windows and Ubuntu.

**Comment by rishflab** [comment] 2021-08-31 05:37
> > Check this out :
> > https://sethforprivacy.com/guides/bitcoin-monero-atomic-swaps/#what-to-do-if-the-swap-fails
> > You can refund between 72 and 128 of your first bitcoin transaction
> 
> Yep great, I need to wakeup at in the middle of the night to ensure I don't lose my money.

Our intention was for the swap cli to wait until block 72 and do this for you but it is broken due a bug (which should be fixed with #705). Then you should be able to resume a swap (using cli args) and it should handle swap execution for you. 

Manual cancel/refund is a temp fix until #705 is merged.

**Comment by kirtspaulding** [comment] 2021-08-31 14:48
Just tried this morning, cancel failed without force tag, but worked after force applied. Refund success.

./swap.exe cancel --swap-id 4a6bbdec-341b-4d18-bfef-b460a3050717
Manually cancelling swap swap_id=4a6bbdec-341b-4d18-bfef-b460a3050717
The cancel transaction cannot be published yet, because the timelock has not expired. Please try again later

**Closed** 2021-08-31 16:40 UTC
Labels: bug, loss-of-funds
