### ISSUE TITLE
[Bug] Failed to broadcast punish transaction

### ISSUE THREAD

**Issue by devbordecraft** [comit-network/xmr-btc-swap#666] opened 2021-08-21 09:10 UTC
When I tried to punish Bob for not sending refund transaction and recovering the monero, the ASB tell me this error : 

![image](https://user-images.githubusercontent.com/36452299/130316776-dda1a157-a192-43e6-bb85-2125e1bacbfd.png)

The state of the swap is : **btc is cancelled**

 ./asb --version
asb 0.8.1-3-gcd5a137

**Comment by devbordecraft** [comment] 2021-08-21 11:58
On another swap with the same case :

![image](https://user-images.githubusercontent.com/36452299/130320844-91733267-e36d-4ee7-ac28-ee320cc56d08.png)

So if I correctly understand according to the logs, the punish transaction tries to broadcast by itself after a set period of time?

**Comment by thomaseizinger** [comment] 2021-08-21 12:53
In the first case, you tried to invoke `punish` before the timelock allowed you to do so. That is what `non-bip68-final` means. You will need to wait for Bob to either publish refund (which means you can refund the Monero) or if he doesn't act at all, you will be able to claim the Bitcoin as a compensation for the locked up Monero.

In the second case, the punish timelock expired but the Bitcoin were actually refunded, you should be able to re-claim your Monero using manual-recovery.

**Comment by thomaseizinger** [comment] 2021-08-21 12:54
Closing because things seem to work as intended, please report if not.

**Closed by thomaseizinger** 2021-08-21 12:54 UTC

**Comment by devbordecraft** [comment] 2021-08-21 15:37
So the first case the bitcoin has been correctly punished, the swap state is : "Done: BtcPunished"  and I have the bitcoin in my wallet. So if I understand correctly, the locked monero are lost forever ?

And for the second case, the state is "Bitcoin punishable"  and when I use manual-recovery it tell me this : 
![image](https://user-images.githubusercontent.com/36452299/130327039-ca98fd1b-643b-4bcf-b594-d15e2fc45cdc.png)

**Comment by thomaseizinger** [comment] 2021-08-23 04:02
> So the first case the bitcoin has been correctly punished, the swap state is : "Done: BtcPunished" and I have the bitcoin in my wallet. So if I understand correctly, the locked monero are lost forever ?

Yes. Punish is a last resort method in case Bob is unresponsive after cancelling the swap. You receive the BTC as a compensation for not being able to claim the Monero.

In the second case, if you have any means of contacting Bob, tell them to refund.

I am not quite sure why it would error with `bad-txns-inputs-missingorspent`. Can you share the funding transaction IDs with me? Feel free to ping me on Matrix.
