### ISSUE TITLE
[1.0 XMR] Provide better feedback when cancel/refund transaction publish fails by parsing electrum error

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#683] opened 2021-08-24 23:20 UTC
As discovered in https://github.com/comit-network/xmr-btc-swap/issues/674, users may try to refund a swap even though that is no longer possible because Alice already punished.

We should catch this case by parsing the error message returned from electrum and display something more informative to the user.

Also, we need to advance the internal state to correctly reflect what happened on the blockchain, otherwise `swap list` returns misleading information.

**Comment by binarybaron** [comment] 2022-08-04 13:03
We use bounties to incentivize development and reward contributors. All issues available for a bounty have the `Bounty 💰 ` label.

To receive the bounty of this issue, you agree to these conditions:

- Your changes must follow the [styling guidelines](https://github.com/comit-network/xmr-btc-swap/blob/master/CONTRIBUTING.md).
- Bounties will be set and awarded at discretion of @binarybaron .
The issues eligible for a bounty are labelled 'Bounty 💰' and have the amount of the bounty specified in the title in this form: [1 XMR].
- An issue is considered resolved when the patch(es) proposed by the contributor is/are merged in the appropriate repository according to terms of the issue.
- The first person who resolves an issue in its entirety will receive the entire amount of the bounty.
- If the issue is resolved collaboratively by more than one person, the reward will be distributed among the contributors
- Let the Maintainers know if you intend to work on a bounty, so that the issue can be assigned to you. Being assigned to an issue doesn't make that issue resolvable only by the assignee. It's meant to avoid duplication of efforts and not to discourage collective works.
- After the issue is resolved, contact @binarybaron and claim your bounty (remember to provide them with a Monero address).

**Comment by binarybaron** [comment] 2022-08-04 13:03
@delta1 Would you be interested in taking this on?

**Comment by delta1** [comment] 2022-08-04 13:22
Yes definitely! Will pick it up after getting #1081 fixed and released for the hard fork

**Comment by binarybaron** [comment] 2022-08-10 13:25
I did start working on this a bit. I'll publish my WIP branch later, if @delta1 or anyone else wants to pick up from where I left

**Comment by binarybaron** [comment] 2022-08-10 15:41
https://github.com/comit-network/xmr-btc-swap/compare/master...binarybaron:xmr-btc-swap:detect-timelocks-manual-refund

**Comment by binarybaron** [comment] 2022-09-12 14:44
Increased bounty to 0.5 XMR! @delta1 @lescuer97

**Comment by delta1** [comment] 2022-09-12 14:48
Nice! Picking this back up tomorrow 👌

**Comment by binarybaron** [comment] 2022-09-27 21:39
Any updates? Have you had time to take a look at this again?

**Comment by delta1** [comment] 2022-09-28 05:09
No updates, sorry have been dealing with personal issues so if somebody else could pick it up that’s totally fine. Otherwise I can get back to it in a couple of weeks.

**Comment by binarybaron** [comment] 2023-06-06 11:24
Increasing bounty to 1 XMR! @lescuer97 @delta1

**Comment by thenhnn** [comment] 2024-03-06 07:14
> @binarybaron I'm increasing the bounty to 1 XMR because I believe this will provide some major benefits in terms of usability!

I'm interested, can I try to implement this?

**Comment by thenhnn** [comment] 2024-03-06 13:31
> @delta1 sure @thenhnn go ahead

Please check #1571

**Comment by patrini32** [comment] 2024-06-04 16:51
Can you check [#1688](https://github.com/comit-network/xmr-btc-swap/pull/1668)?

**Closed** 2024-07-01 21:14 UTC
Labels: enhancement, Bounty 💰, Priority 1
