### ISSUE TITLE
[0.35 XMR] Display swap fees before swap is started

### ISSUE THREAD

**Issue by CryptoMammon** [comit-network/xmr-btc-swap#761] opened 2021-09-08 15:36 UTC
Since we are required to deposit a bit more than the actual swapping amount in order to cover the fees, it would be great if the fees can be displayed to make it easier for people while swapping and to know exactly how much it's needed to be deposited.

**Comment by binarybaron** [comment] 2022-07-26 14:19
We use bounties to incentivize development and reward contributors. All issues available for a bounty have the `Bounty 💰 ` label.

To receive a bounty, you agree to these conditions:

- Your changes must follow the [styling guidelines](https://github.com/comit-network/xmr-btc-swap/blob/master/CONTRIBUTING.md).
- Bounties will be set and awarded at discretion of @binarybaron .
The issues eligible for a bounty are labelled 'Bounty 💰' and have the amount of the bounty specified in the title in this form: [1 XMR].
- An issue is considered resolved when the patch(es) proposed by the contributor is/are merged in the appropriate repository according to terms of the issue.
- The first person who resolves an issue in its entirety will receive the entire amount of the bounty.
- If the issue is resolved collaboratively by more than one person, the reward will be distributed among the contributors
- Let the Maintainers know if you intend to work on a bounty, so that the issue can be assigned to you. Being assigned to an issue doesn't make that issue resolvable only by the assignee. It's meant to avoid duplication of efforts and not to discourage collective works.
- After the issue is resolved, contact @binarybaron and claim your bounty (remember to provide them with a Monero address).

**Comment by delta1** [comment] 2022-07-26 15:39
Hey! I plan to start taking a look at this tomorrow 👌

**Comment by delta1** [comment] 2022-07-29 15:34
I'm almost done with this, should have it PR'd on Monday

**Comment by delta1** [comment] 2022-07-31 12:46
Ready at #1080

**Comment by delta1** [comment] 2022-08-03 12:44
Bounty received, thank you @binarybaron !

**Closed by delta1** 2022-08-03 12:44 UTC
Labels: enhancement, Bounty 💰
