### ISSUE TITLE
[1 XMR] Allow for cooperative release of funds

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#693] opened 2021-08-26 13:17 UTC
The protocol allows for Alice to punish Bob by taking the BTC in case Bob never refunds. This can happen unintentionally as well. See https://github.com/comit-network/xmr-btc-swap/issues/688 for example.

In that case, the two parties would have agreed to a cooperative release of funds. This should be possible to implement if we add:

- A command to the `asb` to print the Monero secret share
- A command to the `cli` to claim the Monero using the secret share

**Comment by binarybaron** [comment] 2023-10-14 23:29
I'd propose that we add a libp2p protocol over which Bob can connect to Alice after Bob has been punished to request Alice to reveal the Monero secret share. Bob can then use that secret to redeem the XMR.

There should be no reason for Alice not to release it if we assume she's good-willed. This will essentially resolve the entire issue of users getting punished in practice.

@delta1 What do you think?

**Comment by binarybaron** [comment] 2023-10-14 23:30
Some more discussion can found here: https://github.com/comit-network/xmr-btc-swap/discussions/713

**Comment by binarybaron** [comment] 2023-10-14 23:31
We use bounties to incentivize development and reward contributors. All issues available for a bounty have the `Bounty 💰 ` label.

To receive the bounty of this issue, you agree to these conditions:

- Your changes must follow the [styling guidelines](https://github.com/comit-network/xmr-btc-swap/blob/master/CONTRIBUTING.md).
- Bounties will be set and awarded at discretion of @binarybaron .
The issues eligible for a bounty are labelled 'Bounty 💰' and have the amount of the bounty specified in the title in this form: [1 XMR].
- An issue is considered resolved when the patch(es) proposed by the contributor is/are merged in the appropriate repository according to terms of the issue.
- The first person who resolves an issue in its entirety will receive the entire amount of the bounty.
- If the issue is resolved collaboratively by more than one person, the reward will be distributed among the contributors
- Let the Maintainers know if you intend to work on a bounty, so that the issue can be assigned to you. Being assigned to an issue doesn't make that issue resolvable only by the assignee. It's meant to avoid duplication of efforts and not to discourage collective works.
- After the issue is resolved, contact @binarybaron and claim your bounty (remember to provide them with a Monero address).

**Comment by delta1** [comment] 2023-10-18 12:15
> I'd propose that we add a libp2p protocol over which Bob can connect to Alice after Bob has been punished to request Alice to reveal the Monero secret share. Bob can then use that secret to redeem the XMR. This behaviour would be invoked by a custom `attempt-cooperative-redeem` command of the CLI.
> 
> There should be no reason for Alice not to release it if we assume she's good-willed. This will essentially resolve the entire issue of users getting punished in practice.
> 
> @delta1 What do you think?

Sounds good, I like it. Will try start on this next week.

**Comment by binarybaron** [comment] 2023-10-23 09:47
> > I'd propose that we add a libp2p protocol over which Bob can connect to Alice after Bob has been punished to request Alice to reveal the Monero secret share. Bob can then use that secret to redeem the XMR. This behaviour would be invoked by a custom `attempt-cooperative-redeem` command of the CLI.
> > 
> > There should be no reason for Alice not to release it if we assume she's good-willed. This will essentially resolve the entire issue of users getting punished in practice.
> > 
> > @delta1 What do you think?
> 
> Sounds good, I like it. Will try start on this next week. 

Awesome

**Comment by delta1** [comment] 2023-11-30 11:30
sorry! no progress yet. will let you know as soon as I have an update.

**Comment by binarybaron** [comment] 2023-12-02 15:14
I've begun work on https://github.com/comit-network/xmr-btc-swap/tree/cooperative-xmr-redeem Feel free to jump in

**Comment by binarybaron** [comment] 2024-05-24 14:30
This would be really cool to get done. I'm busy with a big update for the GUi at the moment. Does anyone want to pick this up?

Otherwise I'll try to get to it in a few weeks.

**Comment by binarybaron** [comment] 2024-06-05 21:45
> I've begun work on https://github.com/comit-network/xmr-btc-swap/tree/cooperative-xmr-redeem Feel free to jump in

TODO:
- [ ] Alice needs to respond with the secret key
- [ ] Bob needs to receive the secret key
- [ ] The CLI needs a command ´attempt-cooperative-release` that takes the swap id and attempts to retrieve the secret key from Alice. It then needs to redeem the Monero.
- [ ] Optional: The CLI should Invoke the same logic describes above in the state machine, if we're in the BtcPunished state

**Comment by patrini32** [comment] 2024-06-07 17:51
> I've begun work on https://github.com/comit-network/xmr-btc-swap/tree/cooperative-xmr-redeem Feel free to jump in

I made a working PoC, going to create a PR tomorrow after reviewing the code.

**Closed** 2024-07-15 08:00 UTC
Labels: enhancement, has-mentoring, Bounty 💰, Priority 1
