### ISSUE TITLE
Failed to complete swap

### ISSUE THREAD

**Issue by paperkut1** [comit-network/xmr-btc-swap#729] opened 2021-09-02 20:36 UTC
Receive this error both times I have tried after upgrade to 0.8.2.

Error: Failed to complete swap

Caused by:
    0: Failed to deserialize bytes into message using CBOR
    1: EOF while parsing a value

**Comment by rishflab** [comment] 2021-09-03 06:58
> Receive this error both times I have tried after upgrade to 0.8.2.
> 
> Error: Failed to complete swap
> 
> Caused by:
> 0: Failed to deserialize bytes into message using CBOR
> 1: EOF while parsing a value

this error could be  logged in many places, could you provide your debug logs so we can figure out where it is happening?

**Comment by TA1002** [comment] 2021-09-05 18:09
I have the exact same issue with 0.8.3. It doesn't appear to be a connection issue, because it failed almost immediately after seeing my BTC deposit transaction (before it was confirmed). I can attempt to start the swap again, and it sees my deposit, starts a new swap, then fails again immediately.

There seems to be no possibility of recovering funds because the swap-id does not show up in my history. 

I won't be replying, just letting you know the OP isn't an anomaly. I'll come back and try again in a month. I really want this project to be successful and I love Monero, but I'm tired of repeatedly losing funds. About half my swaps have been successful, and of those that fail, I was able recover funds only once.

**Comment by GordianSimpul** [comment] 2021-09-27 07:23
FYI, I underwent testing swaps with the majority of the atomic providers today. While I won't name names, testing a particular one failed seven times over 16 hours with the exact same error you referenced and immediately after I deposited my BTC, which may expose a possible issue I will address here in a moment.

There was another provider that consistently did not have enough funds to conduct a swap, even for swaps in the $15-20 range.

There is one provider that publishes a concealed swap id on their webpage and the state of the swap is in - finished or in progress.

Yet another provider I was able to complete two successful swaps with today without any errors.

I still have two more providers to test. I'm interested in seeing the percentage of providers that complete swaps successfully. Granted there is only a handful at this point.

**Note:** All these tests were conducted over tor, with the exception of the first one I mentioned where I tried both tor and clearnet resulting in the same deserialization error.

**Comment by crawfishDavid** [comment] 2021-10-07 23:25
Failed to finish swap, took my back but did not receive xmr my swap ID 

swap_id=77737bd0-4c07-4521-a80d-55da776975cd

What can I do?

**Comment by xmrswapme** [comment] 2021-10-07 23:39
Run: `swap withdraw-btc --address your_bitcoin_address`


Where your Bitcoin address is any address in your private wallet you want the Bitcoin you initially sent transfered back to.

**Comment by crawfishDavid** [comment] 2021-10-07 23:47
If the window was closed how do I search my transfer history?

**Comment by xmrswapme** [comment] 2021-10-07 23:48
Your BTC is stored in a local wallet on your computer. Another option is to run another swap with a different provider and it will use the existing funds to begin a new swap, o/w run the command above.

**Comment by crawfishDavid** [comment] 2021-10-08 05:47
got my funds back, lost my deposit but im ok with that. Thank you for your help.

**Comment by da-kami** [comment] 2021-12-20 04:54
Could not be reproduced using the latest version, closing for now.

**Closed by da-kami** 2021-12-20 04:54 UTC
