### ISSUE TITLE
[1 XMR] Allow ASB to register with multiple rendezvous points

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/xmr-btc-swap#633] opened 2021-07-14 00:29 UTC
At the moment, an ASB can only register with a single rendezvous point.

It would be advantageous if a single ASB instance could register with multiple rendezvous points simultaneously. There are three main areas that need to be changed:

## 1. The ASB's rendezvous `NetworkBehaviour`

The trickiest part about support multiple rendezvous points is to keep track of the registrations and renew them as they expire. [This](https://github.com/comit-network/xmr-btc-swap/blob/52d5f2d83bdd584d734d671198878b4670325d3a/swap/src/asb/network.rs#L173-L343) is where the current magic happens.

The module is reasonably-well supported by tests so I would suggest to start with a test that asserts that we can register with multiple rendezvous points and renew each registration as it expires.

The API changes of the module should be minimal and the rest of the application should still be able to run.

## 2. The configuration

Once the `NetworkBehaviour` supports multiple rendezvous points, extending the [configuration](https://github.com/comit-network/xmr-btc-swap/blob/master/swap/src/asb/config.rs) shouldn't be too hard. We already support a list of multiaddresses for the `listen` key of `network`. Just need to do the same thing for `rendezvous_point`.

## 3. The initial setup wizard

There are multiple ways of how to deal with the initial setup wizard:

1. Either only ask the user once for a rendezvous point and insert that into the list
2. Ask the user in a loop for rendezvous points until they enter an empty address

---

As with all changes, this should definitely come with a changelog entry.

**Comment by protomens** [comment] 2021-08-21 07:18
This would be advantageous for providers and swappers alike. We started our own Rendezvous Endpoint last night and tried to add a second one with similar array syntax for multiaddress as ["", ""]
but obviously was a no go.

**Comment by thomaseizinger** [comment] 2021-08-21 07:51
We currently don't have to bandwidth to implement this but if you need any more instructions on how to do get started, let me know!

**Comment by protomens** [comment] 2021-08-22 03:47
> We currently don't have to bandwidth to implement this but if you would like to tackle it and need any more instructions on how to do get started, let me know!

I manage a couple servers that I would be able try this on. First things first, I have to familiarize myself with Rust. I'm versed in several other languages and sat down with the Rust book this afternoon to get started.

I took a look at the code first and it appears to me that the registration to a rendezvous endpoint happens in:

```
swap/src/asb/network.rs
```

Correct me if I'm wrong.

 I'll also look into libp2p docs and get a more comprehensive grasp on some of the things going on in the code. If, and when, I need some more pointers, I'll be sure to reach out on here. It may take a little while before I start testing this, but I do have a lot of time that I can spend on getting this done. 

Looking forward to contributing!

**Comment by protomens** [comment] 2021-08-22 03:56
Oh, I just noticed your original post that network.rs is where 'the magic happens'.  Good to know. Should've read your post fully before I stumbled my way around the repo.

**Comment by thomaseizinger** [comment] 2021-08-23 04:13
> Oh, I just noticed your original post that network.rs is where 'the magic happens'. Good to know. Should've read your post fully before I stumbled my way around the repo.

I recommend you start with adding a test next to the two that are already there in the module. You shouldn't need a whole lot of libp2p knowledge for that.

**Comment by binarybaron** [comment] 2023-06-06 11:28
We use bounties to incentivize development and reward contributors. All issues available for a bounty have the `Bounty 💰 ` label.

To receive the bounty of this issue, you agree to these conditions:

- Your changes must follow the [styling guidelines](https://github.com/comit-network/xmr-btc-swap/blob/master/CONTRIBUTING.md).
- Bounties will be set and awarded at discretion of @binarybaron .
The issues eligible for a bounty are labelled 'Bounty 💰' and have the amount of the bounty specified in the title in this form: [1 XMR].
- An issue is considered resolved when the patch(es) proposed by the contributor is/are merged in the appropriate repository according to terms of the issue.
- The first person who resolves an issue in its entirety will receive the entire amount of the bounty.
- If the issue is resolved collaboratively by more than one person, the reward will be distributed among the contributors
- Let the Maintainers know if you intend to work on a bounty, so that the issue can be assigned to you. Being assigned to an issue doesn't make that issue resolvable only by the assignee. It's meant to avoid duplication of efforts and not to discourage collective works.
- After the issue is resolved, contact @binarybaron and claim your bounty (remember to provide them with a Monero address).

**Comment by binarybaron** [comment] 2023-06-06 11:30
I added a bounty to this issue. I think making this small change will allow for the peer discovery to become drastically less dependent on centralized infrastructure (e.g the registry run by unstoppableswap.net). 

@delta1 @lescuer97

**Comment by delta1** [comment] 2023-06-06 11:39
Great idea, happy to pick this up as first priority - will let you know about progress

**Comment by delta1** [comment] 2023-06-09 10:26
quick update: I've got a wip with a failing test for multiple rendezvous.

**Comment by binarybaron** [comment] 2023-06-09 13:14
Awesome!

**Comment by binarybaron** [comment] 2023-06-09 13:14
is there a branch I can take look at?

**Comment by icy-ux** [comment] 2023-07-27 09:23
I'll add another 1 XMR to the bounty

**Comment by delta1** [comment] 2023-07-27 12:46
Still busy with this, I have an initial implementation that my testing showed didn't work perfectly so I'm refactoring and improving it. Will post an update early next week!

**Comment by delta1** [comment] 2023-07-31 07:29
got my test working, gotta add the plumbing from the asb/cli front-ends. will update later

**Comment by delta1** [comment] 2023-08-04 12:41
> I'll add another 1 XMR to the bounty

@icy-ux want to give #1417 a spin?

**Comment by binarybaron** [comment] 2023-08-04 14:03
I already merged it. If @icy-ux has any objections we can revert the commit.
@delta1 could you share a XMR address for the payout with us?

**Comment by delta1** [comment] 2023-08-04 15:19
thanks! 

`87escxEg3ucCRdKuCEVrcZWJuAk3MdsXuK9J6jaNVKLLKih7LxCcdoBgC3rCs8KUsMSMQhEJjwCL4b7KAtYD2ykf5EQ2Wue `

**Closed** 2023-08-04 15:20 UTC
Labels: has-mentoring, Bounty 💰

**Comment by icy-ux** [comment] 2023-08-04 22:02
On Fri, Aug 04, 2023 at 08:19:20AM -0700, Byron Hambly wrote:
>`87escxEg3ucCRdKuCEVrcZWJuAk3MdsXuK9J6jaNVKLLKih7LxCcdoBgC3rCs8KUsMSMQhEJjwCL4b7KAtYD2ykf5EQ2Wue `

Paid 1 XMR on the basis of the issue being closed. I have not yet had a
chance to test the code.

Looking forward to the next release!

**Comment by delta1** [comment] 2023-08-07 05:11
> `87escxEg3ucCRdKuCEVrcZWJuAk3MdsXuK9J6jaNVKLLKih7LxCcdoBgC3rCs8KUsMSMQhEJjwCL4b7KAtYD2ykf5EQ2Wue `

@binarybaron can you please pay the bounty to the same address

**Comment by binarybaron** [comment] 2023-08-10 12:57
> > `87escxEg3ucCRdKuCEVrcZWJuAk3MdsXuK9J6jaNVKLLKih7LxCcdoBgC3rCs8KUsMSMQhEJjwCL4b7KAtYD2ykf5EQ2Wue `
> 
> @binarybaron can you please pay the bounty to the same address

I paid 1 XMR to `87escxEg3ucCRdKuCEVrcZWJuAk3MdsXuK9J6jaNVKLLKih7LxCcdoBgC3rCs8KUsMSMQhEJjwCL4b7KAtYD2ykf5EQ2Wue` with txid `926f518b6809cb57e9b74628966c066ff52ffdcf4dfd0a5df350fc282a667043` :)
